### ISSUE TITLE
Nikola workflow

### ISSUE THREAD

**Issue by leingang** [felixfontein/filetreesubs#1]
Can you give a little more detail about how you use this package with Nikola?  I am, as well, and I have a  similar use case.  Is there no way to accomplish the same thing within the templating engine (In my case, Mako)?

**Comment by felixfontein** [comment]
Actually, when I started with Nikola, I tried something similar than you did: injecting the data I wanted into the global context or (before that) into the template contexts themselves (by creating my "own" Nikola template engine which was based on the Mako template engine and simply added more stuff to the context; that was even worse, as the required dependencies weren't inserted). I stopped doing that pretty soon as it turns out that this forces a complete rebuild of every single page if you add a post (or whatever else you add to the context), which took forever (I stopped counting, should be somewhere between 15 and 45 minutes) for my imported blog with several hunderd posts.

Since almost everything on every page doesn't depend on the context, except the sidebar, my next idea was to write that sidebar to disk with a plugin, and then do some postprocessing to insert that into the generated HTML files. Now, to add a post, Nikola still runs for two minutes or so, but only a couple of seconds of them are spent on the postprocessing part (i.e. running filetreesubs).

My workflow looks as follows:
1. My Nikola blog uses the sidebar plugin to generate output/sidebar.inc, and my theme contains something like `<!-- INSERT SIDEBAR HERE -->` where its content should be inserted.
2. I set up filetreesubs to transform `output/` to `final/`, by replacing `<!-- INSERT SIDEBAR HERE -->` in all HTML files with the sidebar.
3. I have a second small Nikola config so I can use `nikola --conf=second-config.py serve` to look at the final result.
4. To deploy, I do a (manual) rsync from `final/` to my webserver. (Nikola can do that too, I think, but I never tried that feature...)

I think I'll create a small example site and upload it to github so you can see how precisely things are done.

**Comment by felixfontein** [comment]
Ok, here it is: https://github.com/felixfontein/filetreesubs-nikola-demo/

**Comment by leingang** [comment]
Thank you very much for doing that.  I'm checking it out now.  Might make a good post for the nikola blog.

**Comment by felixfontein** [comment]
You're welcome! If you have any questions, don't hesitate to ask!
